apiVersion: apps/v1
kind: Deployment
metadata:
  name: authapp-deployment 
  labels:
    app: authapp 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authapp
  template:
    metadata:
      labels:
        app: authapp
    spec:
      containers:
      - name: authapp
        image: authapir.azurecr.io/authrepoimage:latest
        resources:
        env:
           - name: ConnectionString
             value: Server = "tcp:return-server.database.windows.net,1433;Initial Catalog=LoginModels;Persist Security Info=False;User ID=admin1;Password=Subhash@1;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"
        ports:
        - containerPort: 8080
      imagePullSecrets:
        - name: webapisvcsecret  
---


apiVersion: v1
kind: Service
metadata:
  name: authappsvc
spec:
  type: LoadBalancer
  selector:
    app: authapp
  ports:
  - port: 80
